window.SU_DATA = {
  member: 'me',
  members: [
    { id: 'me', name: '婧', role: '本人', avatar: '婧' },
    { id: 'partner', name: '先生', role: '伴侣', avatar: '先' },
    { id: 'child', name: '小宝', role: '孩子', avatar: '宝' },
  ],
  factors: [
    { id: 'glucose', label: '血糖', icon: '🫀', color: '#588ce3', on: true },
    { id: 'walk', label: '步行', icon: '🚶', color: '#3f9f86', on: true },
    { id: 'sleep', label: '睡眠', icon: '😴', color: '#7c6bcf', on: true },
    { id: 'hrv', label: 'HRV', icon: '💓', color: '#d57b6c', on: false },
    { id: 'meds', label: '用药', icon: '💊', color: '#dd9f57', on: true },
    { id: 'weather', label: '天气', icon: '🌤', color: '#96c7f3', on: false },
  ],
  storyVariants: {
    all: '今天午餐后你在第 13 分钟就出门走了——血糖峰压在 <b>134</b>，比你久坐的日子低了约 22。晚餐减半，夜里血糖一直平。二甲双胍早餐后已服，Cary 今日多云转晴，湿度适中。这是顺的一天，神经系统也在往恢复方向走。',
    glucose: '血糖主线：午餐峰 <b>134</b>（&lt;140 ✓），晚餐峰 128，夜间平稳。TIR 今日预计 73%。',
    walk: '步行主线：餐后 <b>13 分钟</b> 开始走 15 分钟，与午餐峰压制高度同步。今日 8.4k 步，午后活动窗口用得好。',
    sleep: '睡眠主线：昨晚深睡 1h42m，预计今晚 HRV 偏高。香薰+红光仪式已就位。',
    hrv: '恢复主线：HRV 基线 +0.4 MAD，静息心率 58（比 28 天基线低 4）。周三 PT 已完成。',
    meds: '用药主线：二甲双胍 500mg 早餐后已服。无胃肠道不适记录。与午餐血糖峰控制节奏一致。',
    weather: '环境主线：Cary 今日 22–29°C，湿度 58%，紫外线中等。这类天气你的午后步行依从率更高（历史 78%）。',
  },
  ledger: [
    { time: '07:30', act: '早餐 蛋+牛油果+三文鱼', body: '峰 116 · 达峰 +45min', icon: '🍳', link: 'glucose' },
    { time: '12:30', act: '午餐 蔬菜→蛋白，无米饭', body: '准备进食', icon: '🥗', link: 'glucose' },
    { time: '12:43', act: '餐后 13 分钟走路 15min', body: '峰压制中 ↓', icon: '🚶', hit: true, link: 'walk' },
    { time: '12:52', act: '午餐峰出现', body: '峰 134 ✓ &lt;140', icon: '📈', hit: true, link: 'glucose' },
    { time: '18:30', act: '晚餐 午餐一半量', body: '峰 128 · 夜间平稳', icon: '🍽️', link: 'glucose' },
    { time: '20:00', act: 'PT 周三组', body: '依从 3/3 本周', icon: '🏋️', link: 'hrv' },
    { time: '22:00', act: '香薰 + 红光', body: '预测 HRV ↑', icon: '🧘', link: 'sleep' },
  ],
  patterns: [
    { id: 'p1', title: '餐后早走路 → 午餐峰下降', level: 'L4', from: '走路', to: '午餐峰', effect: '−18 mg/dL', lag: '即时', n: '14 vs 9', conf: 4, verified: true,
      body: '你的数据 + 文献方向一致。餐后 12 分钟内走路使午餐峰 ↓18 mg/dL（n-of-1 已验证）。',
      links: ['walk', 'glucose'] },
    { id: 'p2', title: '晚练 (>19:00) → 当晚 HRV 偏低', level: 'L2', from: '晚练', to: 'HRV', effect: '−8%', lag: '当晚', n: '11 vs 18', conf: 3, verified: false,
      body: '晚于 19 点训练的夜里，睡眠期 HRV 平均低 8%，静息心率高 3bpm。',
      links: ['hrv', 'sleep'] },
    { id: 'p3', title: '晚餐偏晚 → 次晨空腹血糖偏高', level: 'L2', from: '晚餐时间', to: '空腹血糖', effect: '+6 mg/dL', lag: '次晨', n: '13 vs 21', conf: 4, verified: false,
      body: '晚餐晚于 19:00 的次日清晨，空腹血糖平均 +6 mg/dL。',
      links: ['glucose', 'sleep'] },
    { id: 'p4', title: '正念 ≥10min → 深睡增多', level: 'L3', from: '正念', to: '深睡', effect: '+12 min', lag: '当晚', n: '9 晚', conf: 4, verified: true,
      body: '睡前正念 ≥10 分钟的夜晚，深睡平均 +12 分钟（p≈0.03）。',
      links: ['sleep', 'hrv'] },
    { id: 'p5', title: '高湿度 → 午后活动减少', level: 'L1', from: '湿度>70%', to: '步数', effect: '−1.2k', lag: '当日', n: '观察中', conf: 2, verified: false,
      body: '潮湿天气你的户外步行明显减少，间接影响餐后血糖。样本仍在积累。',
      links: ['weather', 'walk'] },
  ],
  experiments: {
    active: {
      name: '午餐后走路时机',
      progress: 70,
      day: 7, total: 10,
      effect: -18, ci: '9–27', hit: '8/3',
      daily: [
        { d: '6/4', arm: '走', peak: 132, ok: true },
        { d: '6/5', arm: '坐', peak: 151, ok: false },
        { d: '6/6', arm: '走', peak: 128, ok: true },
        { d: '6/7', arm: '坐', peak: 158, ok: false },
        { d: '6/8', arm: '走', peak: 134, ok: true },
        { d: '6/9', arm: '走', peak: 130, ok: true },
        { d: '6/10', arm: '走', peak: 134, ok: true },
      ],
      stats: { meanWalk: 136, meanSit: 154, p: 0.01, power: 0.82 },
    },
    queue: [
      { name: '晚餐时间 → 晨起空腹', status: 'queued' },
      { name: '训练时段 → HRV', status: 'queued' },
    ],
    done: [
      { name: '餐后早走路降午餐峰', effect: '−18 mg/dL', ok: true },
      { name: '睡前正念增深睡', effect: '+12min', ok: true },
      { name: '咖啡因时间 → HRV', effect: 'n.s.', ok: false },
    ],
  },
  familyRecords: {
    me: {
      checkups: [{ date: '2026-03', title: '年度体检', summary: '空腹血糖 5.6，LDL 略高，甲状腺正常', ai: '血糖处于糖尿病前期边缘，建议结合 AGP 与餐时策略讨论。' }],
      meds: [{ name: '二甲双胍', dose: '500mg', sched: '早餐后', note: '与餐同服' }, { name: '维生素 D', dose: '2000IU', sched: '随餐', note: '' }],
      vaccines: [{ name: '流感疫苗', date: '2025-10', next: '2026-10' }, { name: '新冠加强', date: '2025-03', next: '按需' }],
      visits: [{ date: '2026-05-12', dept: '内分泌', note: '讨论餐后血糖模式，医生建议维持当前剂量' }],
    },
    partner: {
      checkups: [{ date: '2025-11', title: '常规体检', summary: '血压正常，血脂良好', ai: '整体健康，建议保持有氧运动。' }],
      meds: [],
      vaccines: [{ name: '流感疫苗', date: '2025-10', next: '2026-10' }],
      visits: [],
    },
    child: {
      checkups: [{ date: '2026-01', title: '儿童保健', summary: '生长发育正常', ai: '身高体重百分位正常。' }],
      meds: [],
      vaccines: [{ name: 'MMR', date: '2025-08', next: '—' }, { name: '水痘', date: '2025-06', next: '—' }],
      visits: [{ date: '2026-02-03', dept: '儿科', note: '春季过敏咨询' }],
    },
  },
  library: [
    { id: 'tir', term: 'TIR', full: 'Time in Range', desc: '血糖在目标范围内的时间占比。你的目标是 70–140 mg/dL。', prevent: '餐后早走路、控制碳水时机可提升 TIR。' },
    { id: 'agp', term: 'AGP', full: 'Ambulatory Glucose Profile', desc: '把多天血糖叠成「典型一天」的轮廓图。', prevent: '看 AGP 可发现固定时段的偏高规律。' },
    { id: 'hrv', term: 'HRV', full: '心率变异性', desc: '心跳间隔波动，反映自主神经系统恢复状态。', prevent: '过晚训练、睡眠不足会降低 HRV。' },
    { id: 'n1', term: 'n-of-1', full: '单病例实验', desc: '以你自己为对照，随机交替两种做法，积累因果证据。', prevent: '比群体研究更贴合你个人的反应。' },
  ],
  diseases: [
    { name: '2 型糖尿病', tags: ['代谢'], warn: '空腹>100 或餐后频繁>140', history: '你曾用餐后步行+减量晚餐有效控制', guide: '二甲双胍餐时服，监测 AGP' },
    { name: '季节性过敏', tags: ['免疫', '环境'], warn: '花粉指数高+湿度变化', history: '小宝春季有过敏史，抗组胺有效', guide: '关注本地花粉预报' },
    { name: '上呼吸道感染', tags: ['呼吸'], warn: '降温+睡眠不足', history: '去年 12 月休息+补水 5 天恢复', guide: '发热>38.5°C 或超 7 天就诊' },
  ],
  alerts: [
    { level: 'warn', text: '明日 Cary 花粉指数偏高，孩子过敏风险↑', action: '查看过敏指南' },
    { level: 'info', text: '本周 TIR 趋势向好 (+6%)，保持餐后步行', action: '查看模式' },
    { level: 'info', text: '流感疫苗距上次已 8 个月，可安排续种', action: '查看疫苗' },
  ],
  glossary: ['TIR', 'AGP', 'HRV', 'CV', '空腹血糖', '二甲双胍', 'n-of-1'],
  aiReplies: {
    tir: 'TIR（Time in Range）是血糖在目标范围内的时间百分比。你今日约 73%，比上周高 6 个百分点。提升 TIR 的关键是控制餐后峰——你身上已验证「餐后早走路」有效。',
    metformin: '二甲双胍主要通过减少肝糖输出和改善胰岛素敏感性起效。常见餐时服法是与早餐或晚餐同服。你目前的 500mg 早餐后方案与午餐峰控制节奏一致；是否调整应结合 AGP 和医生意见。',
    default: '我是溯医助手，可解释指标名词、解读体检报告、梳理用药与家族健康记录。请具体提问，或点选下方术语。本回答仅供参考，不替代医生诊断。',
  },
};
