import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const parent = join(root, '..');
const outDir = join(parent, 'out');
const wwwDir = join(root, 'www');

const DEFAULT_API = 'https://treasurebox-nu.vercel.app';

function readApiUrl(filePath) {
  const lines = readFileSync(filePath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('//')) continue;
    const m = trimmed.match(/TREASUREBOX_API\s*=\s*['"]([^'"]*)['"]/);
    if (m) return m[1];
  }
  return '';
}

let apiUrl = process.env.TREASUREBOX_API || DEFAULT_API;
if (existsSync(join(root, 'config.local.js'))) {
  const local = readApiUrl(join(root, 'config.local.js'));
  if (local) apiUrl = local;
} else if (existsSync(join(root, 'config.example.js'))) {
  const example = readApiUrl(join(root, 'config.example.js'));
  if (example) apiUrl = example;
}

if (!existsSync(outDir)) {
  console.log('Building parent Next.js static export → out/');
  execSync('npm run build', { cwd: parent, stdio: 'inherit', env: { ...process.env, VERCEL: '' } });
}

if (!existsSync(outDir)) {
  throw new Error('Missing out/ — run npm run build in repo root first');
}

if (existsSync(wwwDir)) rmSync(wwwDir, { recursive: true, force: true });
mkdirSync(wwwDir, { recursive: true });
cpSync(outDir, wwwDir, { recursive: true });

const rootConfig = `// Auto-generated by treasurebox-ios/scripts/sync-www.mjs\nwindow.TREASUREBOX_API = '${apiUrl}';\n`;
const secretaryConfig = `// Auto-generated by treasurebox-ios/scripts/sync-www.mjs\nwindow.SECRETARY_API = '${apiUrl}';\n`;

writeFileSync(join(wwwDir, 'config.js'), rootConfig);
mkdirSync(join(wwwDir, 'secretary'), { recursive: true });
writeFileSync(join(wwwDir, 'secretary', 'config.js'), secretaryConfig);

console.log('Synced www/ from', outDir);
console.log('API host:', apiUrl);
